# Generated by Django 4.2.7 on 2023-11-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PriceQuotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("week", models.IntegerField()),
                ("deinze", models.FloatField(max_length=10)),
                ("abc", models.FloatField(max_length=10)),
            ],
        ),
    ]
