# Generated by Django 4.2.7 on 2023-11-12 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("price_quotation", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PriceQuotation",
            new_name="ChickenPriceQuotation",
        ),
    ]
